show DATABASES;

CREATE DATABASE TA22_ej3;

use TA22_ej3;

CREATE TABLE CIENTIFICOS (
DNI VARCHAR(8) PRIMARY KEY,
NomApels NVARCHAR(255) NOT NULL
);

CREATE TABLE PROYECTO (
Id CHAR(4) PRIMARY KEY,
Nombre NVARCHAR(255) NOT NULL,
Horas INT NOT NULL
);

CREATE TABLE ASIGNADO_A (
DNI varchar(8),
FOREIGN KEY (DNI) REFERENCES CIENTIFICOS (DNI),
Id char(4),
FOREIGN KEY (Id) REFERENCES PROYECTO (id),
PRIMARY KEY (DNI, Id)
);
